name: geekly

env:
  ARM_CLIENT_ID:        ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET:    ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_ENVIRONMENT:      ${{ secrets.ARM_ENVIRONMENT }}
  ARM_SUBSCRIPTION_ID:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID:        ${{ secrets.ARM_TENANT_ID }}
  AZURE_E_AVD_SP_CREDS: ${{ secrets.AZURE_E_AVD_SP_CREDS }}

  AUTH_KEY_VAULT: '{
    name:              "${{ inputs.AuthKeyVaultName }}",
    resourceGroupName: "${{ inputs.AuthKeyVaultResourceGroupName }}",
    subscriptionId:    "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  }'
  AZURE_TAGS: '{
    deployment_source: "GitHub Actions",
    deployment_tool:   "PowerShell",
    environment:       "${{ inputs.Environment }}",
    owner:             "Temp",
    project:           "Geekly"
  }'
  CREDENTIALS: '{
    "clientId":       "${{ secrets.ARM_CLIENT_ID }}",
    "clientSecret":   "${{ secrets.ARM_CLIENT_SECRET }}",
    "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
    "tenantId":       "${{ secrets.ARM_TENANT_ID }}"
  }'
  LOCATION: "${{ inputs.Location }}"
  LOG_ANALYTICS_WORKSPACE: '{
    name:              "${{ inputs.LogAnalyticsWorkspaceName }}",
    resourceGroupName: "${{ inputs.LogAnalyticsWorkspaceResourceGroup }}",
    subscriptionId:    "${{ secrets.ARM_SUBSCRIPTION_ID }}",
    workspaceId:       "${{ inputs.LogAnalyticsWorkspaceId }}"
  }'

on:
  workflow_call:
    inputs:
      AppConfigurationStoreName:
        required: true
        type: string
      AuthKeyVaultName:
        required: true
        type: string
      AuthKeyVaultResourceGroupName:
        required: true
        type: string
      Environment:
        required: true
        type: string
      Location:
        required: true
        type: string
      ResourceGroupName:
        required: false
        type: string
      FunctionAppName:
        required: true
        type: string
      LogAnalyticsWorkspaceName:
        required: true
        type: string
      LogAnalyticsWorkspaceResourceGroup:
        required: true
        type: string
      LogAnalyticsWorkspaceId:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_ENVIRONMENT:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      AZURE_E_AVD_SP_CREDS:
        required: false

jobs:
  function-app:
    name:        Deploy Geekly Function App
    runs-on:     ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.2.2

      - name: Login to AVD Subscription
        uses: azure/login@v2.3.0
        with:
          creds:              ${{ env.CREDENTIALS }}
          environment:        "AzureUSGovernment"
          enable-AzPSSession: true

      - name: Deploy Geekly Function App
        uses: azure/powershell@v2
        with:
          azPSVersion:         "latest"
          failOnStandardError: true
          inlineScript: |
            ./bicep/deploy-function-app/Invoke-Deployment.ps1 `
                -AppConfigurationStoreName "${{ inputs.AppConfigurationStoreName }}" `
                -FunctionAppName "${{ inputs.FunctionAppName }}" `
                -ResourceGroupName "${{ inputs.ResourceGroupName }}"

      - name: Deploy Function App Zip Package
        uses: Azure/functions-action@v1.5.3
        with:
          app-name: ${{ inputs.FunctionAppName }}
          package: ./function-app

      - name:  Show Function App Zip Package Size
        shell: bash
        run:   find /home/runner/work/_temp -iname "temp_web_package_*.zip" -exec ls -1hSs {} +
