name: sbx-clean-up

env:
  ARM_CLIENT_ID:        ${{ secrets.AZURE_P_CAZ_AVD_IAC_SPN_CLIENT_ID }}
  ARM_CLIENT_SECRET:    ${{ secrets.AZURE_P_CAZ_AVD_IAC_SPN_CLIENT_SECRET }}
  ARM_ENVIRONMENT:      usgovernment
  ARM_SUBSCRIPTION_ID:  ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID:        ${{ secrets.AZURE_TENANT_ID }}
  AZURE_E_AVD_SP_CREDS: ${{ secrets.AZURE_P_CAZ_AVD_IAC_SPN }}

  COMPUTE_SUBSCRIPTION_ID: "${{ vars.AZURE_CAZ_W0FUAA_AVD_GKY01A_S_IL5_SUB_ID }}"
  CREDENTIALS: '{
    "clientId":       "${{ secrets.AZURE_P_CAZ_AVD_IAC_SPN_CLIENT_ID }}",
    "clientSecret":   "${{ secrets.AZURE_P_CAZ_AVD_IAC_SPN_CLIENT_SECRET }}",
    "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}",
    "tenantId":       "${{ secrets.AZURE_TENANT_ID }}"
  }'
  HOST_POOL_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  clean-up:
    name:        Cleanup Geekly Resources
    runs-on:     ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.2.2

      - name: Login to AVD Subscription
        uses: azure/login@v2.3.0
        with:
          creds:              ${{ env.CREDENTIALS }}
          environment:        "AzureUSGovernment"
          enable-AzPSSession: true

      - name: Cleanup Test Resources
        uses: azure/powershell@v2
        with:
          azPSVersion:         "latest"
          failOnStandardError: true
          inlineScript:        ./workflow-scripts/Remove-DeploymentResourceGroup.ps1 -PullRequestNumber ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
